/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AppWebhooksRouteImport } from './routes/_app.webhooks'
import { Route as AppUsageRouteImport } from './routes/_app.usage'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppServiceHealthRouteImport } from './routes/_app.service-health'
import { Route as AppPlaygroundRouteImport } from './routes/_app.playground'
import { Route as AppNumbersRouteImport } from './routes/_app.numbers'
import { Route as AppInboxRouteImport } from './routes/_app.inbox'
import { Route as AppContactsRouteImport } from './routes/_app.contacts'
import { Route as AppCallsRouteImport } from './routes/_app.calls'
import { Route as AppBillingRouteImport } from './routes/_app.billing'
import { Route as AppApiKeysRouteImport } from './routes/_app.api-keys'
import { Route as AppAgentsRouteImport } from './routes/_app.agents'
import { Route as AppNumbersNumberIdRouteImport } from './routes/_app.numbers.$numberId'
import { Route as AppCallsCallIdRouteImport } from './routes/_app.calls.$callId'
import { Route as AppAgentsAgentIdRouteImport } from './routes/_app.agents.$agentId'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWebhooksRoute = AppWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => AppRoute,
} as any)
const AppUsageRoute = AppUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppServiceHealthRoute = AppServiceHealthRouteImport.update({
  id: '/service-health',
  path: '/service-health',
  getParentRoute: () => AppRoute,
} as any)
const AppPlaygroundRoute = AppPlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => AppRoute,
} as any)
const AppNumbersRoute = AppNumbersRouteImport.update({
  id: '/numbers',
  path: '/numbers',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsRoute = AppContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AppRoute,
} as any)
const AppCallsRoute = AppCallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppApiKeysRoute = AppApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsRoute = AppAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AppRoute,
} as any)
const AppNumbersNumberIdRoute = AppNumbersNumberIdRouteImport.update({
  id: '/$numberId',
  path: '/$numberId',
  getParentRoute: () => AppNumbersRoute,
} as any)
const AppCallsCallIdRoute = AppCallsCallIdRouteImport.update({
  id: '/$callId',
  path: '/$callId',
  getParentRoute: () => AppCallsRoute,
} as any)
const AppAgentsAgentIdRoute = AppAgentsAgentIdRouteImport.update({
  id: '/$agentId',
  path: '/$agentId',
  getParentRoute: () => AppAgentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/agents': typeof AppAgentsRouteWithChildren
  '/api-keys': typeof AppApiKeysRoute
  '/billing': typeof AppBillingRoute
  '/calls': typeof AppCallsRouteWithChildren
  '/contacts': typeof AppContactsRoute
  '/inbox': typeof AppInboxRoute
  '/numbers': typeof AppNumbersRouteWithChildren
  '/playground': typeof AppPlaygroundRoute
  '/service-health': typeof AppServiceHealthRoute
  '/settings': typeof AppSettingsRoute
  '/usage': typeof AppUsageRoute
  '/webhooks': typeof AppWebhooksRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/agents/$agentId': typeof AppAgentsAgentIdRoute
  '/calls/$callId': typeof AppCallsCallIdRoute
  '/numbers/$numberId': typeof AppNumbersNumberIdRoute
}
export interface FileRoutesByTo {
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/agents': typeof AppAgentsRouteWithChildren
  '/api-keys': typeof AppApiKeysRoute
  '/billing': typeof AppBillingRoute
  '/calls': typeof AppCallsRouteWithChildren
  '/contacts': typeof AppContactsRoute
  '/inbox': typeof AppInboxRoute
  '/numbers': typeof AppNumbersRouteWithChildren
  '/playground': typeof AppPlaygroundRoute
  '/service-health': typeof AppServiceHealthRoute
  '/settings': typeof AppSettingsRoute
  '/usage': typeof AppUsageRoute
  '/webhooks': typeof AppWebhooksRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/': typeof AppIndexRoute
  '/agents/$agentId': typeof AppAgentsAgentIdRoute
  '/calls/$callId': typeof AppCallsCallIdRoute
  '/numbers/$numberId': typeof AppNumbersNumberIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/_app/agents': typeof AppAgentsRouteWithChildren
  '/_app/api-keys': typeof AppApiKeysRoute
  '/_app/billing': typeof AppBillingRoute
  '/_app/calls': typeof AppCallsRouteWithChildren
  '/_app/contacts': typeof AppContactsRoute
  '/_app/inbox': typeof AppInboxRoute
  '/_app/numbers': typeof AppNumbersRouteWithChildren
  '/_app/playground': typeof AppPlaygroundRoute
  '/_app/service-health': typeof AppServiceHealthRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/usage': typeof AppUsageRoute
  '/_app/webhooks': typeof AppWebhooksRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_app/': typeof AppIndexRoute
  '/_app/agents/$agentId': typeof AppAgentsAgentIdRoute
  '/_app/calls/$callId': typeof AppCallsCallIdRoute
  '/_app/numbers/$numberId': typeof AppNumbersNumberIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/login'
    | '/onboarding'
    | '/agents'
    | '/api-keys'
    | '/billing'
    | '/calls'
    | '/contacts'
    | '/inbox'
    | '/numbers'
    | '/playground'
    | '/service-health'
    | '/settings'
    | '/usage'
    | '/webhooks'
    | '/auth/callback'
    | '/agents/$agentId'
    | '/calls/$callId'
    | '/numbers/$numberId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/accept-invite'
    | '/login'
    | '/onboarding'
    | '/agents'
    | '/api-keys'
    | '/billing'
    | '/calls'
    | '/contacts'
    | '/inbox'
    | '/numbers'
    | '/playground'
    | '/service-health'
    | '/settings'
    | '/usage'
    | '/webhooks'
    | '/auth/callback'
    | '/'
    | '/agents/$agentId'
    | '/calls/$callId'
    | '/numbers/$numberId'
  id:
    | '__root__'
    | '/_app'
    | '/accept-invite'
    | '/login'
    | '/onboarding'
    | '/_app/agents'
    | '/_app/api-keys'
    | '/_app/billing'
    | '/_app/calls'
    | '/_app/contacts'
    | '/_app/inbox'
    | '/_app/numbers'
    | '/_app/playground'
    | '/_app/service-health'
    | '/_app/settings'
    | '/_app/usage'
    | '/_app/webhooks'
    | '/auth/callback'
    | '/_app/'
    | '/_app/agents/$agentId'
    | '/_app/calls/$callId'
    | '/_app/numbers/$numberId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/webhooks': {
      id: '/_app/webhooks'
      path: '/webhooks'
      fullPath: '/webhooks'
      preLoaderRoute: typeof AppWebhooksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/usage': {
      id: '/_app/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof AppUsageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/service-health': {
      id: '/_app/service-health'
      path: '/service-health'
      fullPath: '/service-health'
      preLoaderRoute: typeof AppServiceHealthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/playground': {
      id: '/_app/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof AppPlaygroundRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/numbers': {
      id: '/_app/numbers'
      path: '/numbers'
      fullPath: '/numbers'
      preLoaderRoute: typeof AppNumbersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inbox': {
      id: '/_app/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contacts': {
      id: '/_app/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AppContactsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calls': {
      id: '/_app/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof AppCallsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/api-keys': {
      id: '/_app/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof AppApiKeysRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agents': {
      id: '/_app/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AppAgentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/numbers/$numberId': {
      id: '/_app/numbers/$numberId'
      path: '/$numberId'
      fullPath: '/numbers/$numberId'
      preLoaderRoute: typeof AppNumbersNumberIdRouteImport
      parentRoute: typeof AppNumbersRoute
    }
    '/_app/calls/$callId': {
      id: '/_app/calls/$callId'
      path: '/$callId'
      fullPath: '/calls/$callId'
      preLoaderRoute: typeof AppCallsCallIdRouteImport
      parentRoute: typeof AppCallsRoute
    }
    '/_app/agents/$agentId': {
      id: '/_app/agents/$agentId'
      path: '/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AppAgentsAgentIdRouteImport
      parentRoute: typeof AppAgentsRoute
    }
  }
}

interface AppAgentsRouteChildren {
  AppAgentsAgentIdRoute: typeof AppAgentsAgentIdRoute
}

const AppAgentsRouteChildren: AppAgentsRouteChildren = {
  AppAgentsAgentIdRoute: AppAgentsAgentIdRoute,
}

const AppAgentsRouteWithChildren = AppAgentsRoute._addFileChildren(
  AppAgentsRouteChildren,
)

interface AppCallsRouteChildren {
  AppCallsCallIdRoute: typeof AppCallsCallIdRoute
}

const AppCallsRouteChildren: AppCallsRouteChildren = {
  AppCallsCallIdRoute: AppCallsCallIdRoute,
}

const AppCallsRouteWithChildren = AppCallsRoute._addFileChildren(
  AppCallsRouteChildren,
)

interface AppNumbersRouteChildren {
  AppNumbersNumberIdRoute: typeof AppNumbersNumberIdRoute
}

const AppNumbersRouteChildren: AppNumbersRouteChildren = {
  AppNumbersNumberIdRoute: AppNumbersNumberIdRoute,
}

const AppNumbersRouteWithChildren = AppNumbersRoute._addFileChildren(
  AppNumbersRouteChildren,
)

interface AppRouteChildren {
  AppAgentsRoute: typeof AppAgentsRouteWithChildren
  AppApiKeysRoute: typeof AppApiKeysRoute
  AppBillingRoute: typeof AppBillingRoute
  AppCallsRoute: typeof AppCallsRouteWithChildren
  AppContactsRoute: typeof AppContactsRoute
  AppInboxRoute: typeof AppInboxRoute
  AppNumbersRoute: typeof AppNumbersRouteWithChildren
  AppPlaygroundRoute: typeof AppPlaygroundRoute
  AppServiceHealthRoute: typeof AppServiceHealthRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppUsageRoute: typeof AppUsageRoute
  AppWebhooksRoute: typeof AppWebhooksRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgentsRoute: AppAgentsRouteWithChildren,
  AppApiKeysRoute: AppApiKeysRoute,
  AppBillingRoute: AppBillingRoute,
  AppCallsRoute: AppCallsRouteWithChildren,
  AppContactsRoute: AppContactsRoute,
  AppInboxRoute: AppInboxRoute,
  AppNumbersRoute: AppNumbersRouteWithChildren,
  AppPlaygroundRoute: AppPlaygroundRoute,
  AppServiceHealthRoute: AppServiceHealthRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppUsageRoute: AppUsageRoute,
  AppWebhooksRoute: AppWebhooksRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
